/* ============================================================
   LocalView — Deployed Websites
   Edit this file to add/update your Vercel projects.
   ============================================================ */
window.WEBSITES = [
  {
    id: "apple-notes-clone",
    name: "apple-notes-clone",
    displayName: "Apple Notes Clone",
    framework: "Next.js",
    deployed: false,
    url: null,
    vercelProject: "apple-no",
    github: "rajamails19/apple-notes-clone",
    branch: "main",
    lastCommit: "pinch image fix 2",
    lastDeploy: "2d ago",
    about: "A pixel-faithful clone of Apple Notes with real-time sync, folders, and rich-text editing.",
    tags: ["notes", "productivity", "fullstack"],
  },
  {
    id: "gptteluguwithraja",
    name: "gptteluguwithraja",
    displayName: "GPT Telugu With Raja",
    framework: "Next.js",
    deployed: true,
    url: "https://gptteluguwithraja.vercel.app",
    vercelProject: "gptteluguwithraja",
    github: "rajamails19/gpttelugu",
    branch: "main",
    lastCommit: "Fix Android TTS CORS support",
    lastDeploy: "Jun 12",
    about: "A Telugu language AI assistant powered by GPT, with text-to-speech support.",
    tags: ["ai", "telugu", "language"],
  },
  {
    id: "telugu-trace-kids",
    name: "telugu-trace-kids",
    displayName: "Telugu Trace Kids",
    framework: "Node.js",
    deployed: false,
    url: null,
    vercelProject: "telugu-t",
    github: "rajamails19/telugu-trace-kids",
    branch: "main",
    lastCommit: "gitignore: add server/port",
    lastDeploy: "Jun 12",
    about: "Kids app to learn tracing Telugu letters with stroke-order guides and audio cues.",
    tags: ["kids", "education", "telugu"],
  },
  {
    id: "claudeteluguwithraja",
    name: "claudeteluguwithraja",
    displayName: "Claude Telugu With Raja",
    framework: "Next.js",
    deployed: true,
    url: "https://claudeteluguwithraja.vercel.app",
    vercelProject: "claudeteluguwithraja",
    github: "rajamails19/claudeteluguwithraja",
    branch: "main",
    lastCommit: "cover images colors one",
    lastDeploy: "Jun 9",
    about: "A Telugu language learning platform powered by Claude AI.",
    tags: ["ai", "telugu", "claude"],
  },
  {
    id: "kidshabits",
    name: "kidshabits",
    displayName: "Kids Habits",
    framework: "Vite",
    deployed: true,
    url: "https://kidshabits-tan.vercel.app",
    vercelProject: "kidshabits",
    github: "rajamails19/kidshabits",
    branch: "main",
    lastCommit: "kids habits commit",
    lastDeploy: "Jun 8",
    about: "A habit tracker app for kids with streaks, rewards, and parental oversight.",
    tags: ["kids", "habits", "productivity"],
  },
  {
    id: "typing-kids-app",
    name: "typing-kids-app",
    displayName: "KeyQuest Typing App",
    framework: "Vite",
    deployed: false,
    url: null,
    vercelProject: "keyquest",
    github: "rajamails19/typing-kids-app",
    branch: "main",
    lastCommit: "Initial commit: KeyQuest kids typing app",
    lastDeploy: "May 30",
    about: "A fun typing game for kids with animated characters and level progression.",
    tags: ["kids", "typing", "game"],
  },
  {
    id: "formafitness",
    name: "formafitness",
    displayName: "Forma Fitness",
    framework: "Next.js",
    deployed: true,
    url: "https://formafitness-nine.vercel.app",
    vercelProject: "formafitness",
    github: "rajamails19/formafitness",
    branch: "main",
    lastCommit: "fitness app",
    lastDeploy: "Jun 8",
    about: "A workout-tracking PWA with guided routines, progress charts and streaks.",
    tags: ["fitness", "health", "pwa"],
  },
  {
    id: "telugu-tales",
    name: "telugu-tales",
    displayName: "Telugu Tales",
    framework: "Next.js",
    deployed: false,
    url: null,
    vercelProject: "telugu-tales",
    github: "rajamails19/telugu-tales",
    branch: "main",
    lastCommit: "Initial commit: Telugu Tales Next.js app",
    lastDeploy: "May 30",
    about: "A story platform for Telugu children with audio narration and illustrations.",
    tags: ["kids", "stories", "telugu"],
  },
  {
    id: "react-docs-platform",
    name: "react-docs-platform",
    displayName: "React Docs Platform",
    framework: "Next.js",
    deployed: true,
    url: "https://react-docs-platform.vercel.app",
    vercelProject: "react-docs-platform",
    github: "rajamails19/react-docs-platform",
    branch: "main",
    lastCommit: "feat: collapsible left sidebar with edge handle",
    lastDeploy: "May 25",
    about: "An interactive React tutorial platform with live code editor and docs.",
    tags: ["docs", "react", "tutorial"],
  },
  {
    id: "chai-raja-vibes",
    name: "chai-raja-vibes",
    displayName: "Chai Raja Vibes",
    framework: "Vite",
    deployed: true,
    url: "https://chai-raja-vibes-4add6471.vercel.app",
    vercelProject: "chai-raja-vibes",
    github: "rajamails19/chai-raja-vibes",
    branch: "main",
    lastCommit: "Merge pull request #1",
    lastDeploy: "May 15",
    about: "A chill music and vibes app for tea lovers.",
    tags: ["music", "vibes", "fun"],
  },
  {
    id: "raja-code-quiz",
    name: "raja-code-quiz",
    displayName: "Raja Code Quiz",
    framework: "Vite",
    deployed: true,
    url: "https://raja-code-quiz.vercel.app",
    vercelProject: "raja-code-quiz",
    github: "rajamails19/raja-code-quiz",
    branch: "main",
    lastCommit: "DuplicateLine and Warning message",
    lastDeploy: "Apr 23",
    about: "A coding quiz platform to test your programming knowledge.",
    tags: ["quiz", "coding", "learning"],
  },
  {
    id: "tic-tac-toe",
    name: "tic-tac-toe",
    displayName: "Tic Tac Toe",
    framework: "Vite",
    deployed: false,
    url: null,
    vercelProject: "tic-tac-toe",
    github: "rajamails19/tic-tac-toe",
    branch: "main",
    lastCommit: "Initial commit: Tic Tac Toe app",
    lastDeploy: "May 30",
    about: "Classic Tic Tac Toe game with animations.",
    tags: ["game", "fun"],
  },
  {
    id: "chess-for-fun",
    name: "chess-for-fun",
    displayName: "Chess For Fun",
    framework: "Vite",
    deployed: false,
    url: null,
    vercelProject: "chess-for-fun",
    github: "rajamails19/chess-for-fun",
    branch: "main",
    lastCommit: "Initial commit: Chess for Fun app",
    lastDeploy: "May 30",
    about: "A browser chess game with AI opponent.",
    tags: ["chess", "game", "ai"],
  },
];

/* ============================================================
   Per-site icons — unique SVG glyphs (set via dangerouslySetInnerHTML)
   ============================================================ */
window.SITE_ICONS = {
  "apple-notes-clone":     { bg: ["#1a1a2e","#16213e"], svg: '<svg viewBox="0 0 40 40" fill="none"><rect x="8" y="6" width="24" height="28" rx="4" fill="rgba(255,255,255,.12)" stroke="rgba(255,255,255,.3)" stroke-width="1.2"/><path d="M13 13h14M13 18h14M13 23h9" stroke="#fff" stroke-width="1.8" stroke-linecap="round"/><circle cx="28" cy="30" r="5" fill="#ffcf6b"/><path d="M26 30l1.5 1.5L30 28" stroke="#1a1a2e" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>' },
  "gptteluguwithraja":     { bg: ["#0f2027","#203a43"], svg: '<svg viewBox="0 0 40 40" fill="none"><circle cx="20" cy="20" r="13" fill="rgba(255,255,255,.08)" stroke="rgba(255,255,255,.2)" stroke-width="1.2"/><circle cx="20" cy="20" r="5" fill="#10a37f"/><path d="M20 7v4M20 29v4M7 20h4M29 20h4M11 11l2.8 2.8M26.2 26.2L29 29M11 29l2.8-2.8M26.2 13.8L29 11" stroke="#10a37f" stroke-width="1.5" stroke-linecap="round"/></svg>' },
  "telugu-trace-kids":     { bg: ["#1a0a2e","#2d1b69"], svg: '<svg viewBox="0 0 40 40" fill="none"><path d="M10 30 Q14 14 20 12 Q26 10 28 18 Q30 26 24 28" stroke="#a78bfa" stroke-width="2.2" stroke-linecap="round" fill="none"/><circle cx="10" cy="30" r="2.5" fill="#f59e0b"/><path d="M22 24l4 4-2 1-1-2-1 2-2-1 2-4z" fill="#f59e0b"/></svg>' },
  "claudeteluguwithraja":  { bg: ["#1a0f0a","#2d1a0a"], svg: '<svg viewBox="0 0 40 40" fill="none"><circle cx="20" cy="20" r="13" fill="rgba(232,147,85,.15)" stroke="rgba(232,147,85,.4)" stroke-width="1.2"/><path d="M14 26 Q12 20 15 16 Q18 12 22 13 Q27 14 27 19 Q27 24 23 26 Q20 27 17 26" stroke="#e89355" stroke-width="1.8" stroke-linecap="round" fill="none"/><circle cx="20" cy="19" r="3.5" fill="#e89355" opacity=".6"/></svg>' },
  "kidshabits":            { bg: ["#0a1628","#0d2137"], svg: '<svg viewBox="0 0 40 40" fill="none"><path d="M20 8l2.9 6 6.6.9-4.8 4.7 1.1 6.6L20 23.3l-5.9 3 1.1-6.6L10.5 15l6.6-.9L20 8z" fill="#fbbf24" stroke="#f59e0b" stroke-width=".8"/><circle cx="20" cy="32" r="3" fill="rgba(251,191,36,.3)" stroke="#fbbf24" stroke-width="1.2"/><path d="M17 32h6" stroke="#fbbf24" stroke-width="1.2" stroke-linecap="round"/></svg>' },
  "typing-kids-app":       { bg: ["#0a0a1a","#111132"], svg: '<svg viewBox="0 0 40 40" fill="none"><rect x="6" y="14" width="28" height="16" rx="3" fill="rgba(255,255,255,.08)" stroke="rgba(255,255,255,.25)" stroke-width="1.2"/><rect x="10" y="18" width="4" height="4" rx="1" fill="#818cf8"/><rect x="16" y="18" width="4" height="4" rx="1" fill="#818cf8"/><rect x="22" y="18" width="4" height="4" rx="1" fill="#818cf8"/><rect x="12" y="24" width="16" height="3" rx="1.5" fill="#6366f1"/><path d="M20 9l-2 3h4l-2-3z" fill="#fbbf24"/></svg>' },
  "formafitness":          { bg: ["#0a0f0a","#0d1f0d"], svg: '<svg viewBox="0 0 40 40" fill="none"><rect x="5" y="18" width="4" height="6" rx="2" fill="#4ade80"/><rect x="31" y="18" width="4" height="6" rx="2" fill="#4ade80"/><rect x="8" y="19" width="6" height="4" rx="1" fill="#22c55e"/><rect x="26" y="19" width="6" height="4" rx="1" fill="#22c55e"/><rect x="14" y="17" width="12" height="8" rx="2" fill="#16a34a"/><circle cx="20" cy="13" r="3.5" fill="rgba(74,222,128,.3)" stroke="#4ade80" stroke-width="1.2"/></svg>' },
  "telugu-tales":          { bg: ["#1a0a1a","#2a0a3a"], svg: '<svg viewBox="0 0 40 40" fill="none"><rect x="8" y="8" width="18" height="24" rx="3" fill="rgba(192,132,252,.15)" stroke="rgba(192,132,252,.4)" stroke-width="1.2"/><rect x="12" y="8" width="18" height="24" rx="3" fill="rgba(192,132,252,.1)" stroke="rgba(192,132,252,.25)" stroke-width="1.2"/><path d="M13 15h10M13 19h8M13 23h6" stroke="#c084fc" stroke-width="1.5" stroke-linecap="round"/><path d="M24 28l4-4 2 2-4 4-2-2z" fill="#f59e0b" stroke="#f59e0b" stroke-width=".5"/></svg>' },
  "react-docs-platform":   { bg: ["#0a1a2e","#0d2040"], svg: '<svg viewBox="0 0 40 40" fill="none"><circle cx="20" cy="20" r="3" fill="#61dafb"/><ellipse cx="20" cy="20" rx="13" ry="5" stroke="#61dafb" stroke-width="1.4" fill="none"/><ellipse cx="20" cy="20" rx="13" ry="5" stroke="#61dafb" stroke-width="1.4" fill="none" transform="rotate(60 20 20)"/><ellipse cx="20" cy="20" rx="13" ry="5" stroke="#61dafb" stroke-width="1.4" fill="none" transform="rotate(120 20 20)"/></svg>' },
  "chai-raja-vibes":       { bg: ["#1a0a08","#2d1208"], svg: '<svg viewBox="0 0 40 40" fill="none"><path d="M12 16h16l-2 12H14L12 16z" fill="rgba(251,146,60,.15)" stroke="rgba(251,146,60,.5)" stroke-width="1.2"/><path d="M28 19h3a3 3 0 0 1 0 6h-3" stroke="#fb923c" stroke-width="1.5" stroke-linecap="round"/><path d="M15 13 Q16 10 20 10 Q24 10 25 13" stroke="#fb923c" stroke-width="1.2" stroke-linecap="round" fill="none"/><path d="M16 28h8" stroke="rgba(251,146,60,.6)" stroke-width="1.5" stroke-linecap="round"/></svg>' },
  "raja-code-quiz":        { bg: ["#0a0a1a","#12122a"], svg: '<svg viewBox="0 0 40 40" fill="none"><circle cx="20" cy="20" r="12" fill="rgba(99,102,241,.12)" stroke="rgba(99,102,241,.4)" stroke-width="1.2"/><path d="M15 17c0-3 2-5 5-5s5 2 5 5c0 2-1 3-3 4v2" stroke="#818cf8" stroke-width="1.8" stroke-linecap="round"/><circle cx="20" cy="28" r="1.5" fill="#818cf8"/></svg>' },
  "tic-tac-toe":           { bg: ["#0f0a1a","#1a1030"], svg: '<svg viewBox="0 0 40 40" fill="none"><path d="M16 8v24M24 8v24M8 16h24M8 24h24" stroke="rgba(255,255,255,.25)" stroke-width="1.5" stroke-linecap="round"/><circle cx="12" cy="12" r="3" stroke="#f87171" stroke-width="1.8" fill="none"/><path d="M20 19l6 6M26 19l-6 6" stroke="#60a5fa" stroke-width="1.8" stroke-linecap="round"/><circle cx="12" cy="28" r="3" stroke="#f87171" stroke-width="1.8" fill="none"/></svg>' },
  "chess-for-fun":         { bg: ["#0a0a0a","#1a1a1a"], svg: '<svg viewBox="0 0 40 40" fill="none"><rect x="8" y="28" width="24" height="4" rx="1.5" fill="rgba(255,255,255,.4)"/><rect x="12" y="24" width="16" height="5" rx="1" fill="rgba(255,255,255,.3)"/><rect x="14" y="16" width="12" height="9" rx="1" fill="rgba(255,255,255,.2)"/><path d="M17 16v-3h6v3" stroke="rgba(255,255,255,.5)" stroke-width="1.2" stroke-linecap="round"/><path d="M17 13l3-5 3 5" stroke="rgba(255,255,255,.6)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/><circle cx="20" cy="8" r="2" fill="rgba(255,255,255,.7)"/></svg>' },
};
